language: python
python:
  - "3.6"
  - "2.7"

services:
  - mysql
  - mongodb

install:
    - pip install -r tests/requirements.txt
    - pip install codecov

before_script:
    - mysql -V && mongo --version
    - mysql -e 'create database if not exists tripitaka_test;'
    - mysql tripitaka_test < model/init.sql;
    - python tests/add_pages.py --json_path=tests/data --db_name=tripitaka_test

script:
    - ./run_tests.py --cov=controller --cov-report=term tests

after_success:
    - codecov
