cookie_secret: 'iS2rCQ1FSrG4UOTAboVhqkY5RtRLBkA6ketwS7fMVbo='

database:
  host: 127.0.0.1
  port: 3306
  name: tripitaka
  user: root
  password: jet123789

site:
  name: 大藏经平台
  keywords: 大藏经,古籍数字化,tripitaka
  description: 大藏经古籍数字化平台
  domain: q.tripitakas.net
  # https:
  #  certfile: tripitaka.crt
  #  keyfile: tripitaka.key
