cookie_secret: '3uHFa8fuSiqeWNO6shr8TzkiRTdluEkBpxaeZ26J0Og='
database:
  host: 127.0.0.1
  port: 3306
  dbname: tripitaka
  dbuser: root
  password:

site:
  name: 大藏经平台
  keywords: 大藏经,古籍数字化,tripitaka
  description: 大藏经古籍数字化平台
  domain: yoursite.cn
  # https:
  #  certfile: yoursite.crt
  #  keyfile: yoursite.key
